{% set version = "3.1.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rpart.plot
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rpart.plot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rpart.plot/rpart.plot_{{ version }}.tar.gz
  sha256: 30736240058df21a96d10912a091d938f821d521a3bc4efb9aa4ef6fb233024d

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rpart >=4.1_15
  run:
    - r-base
    - r-rpart >=4.1_15

test:
  commands:
    - $R -e "library('rpart.plot')"           # [not win]
    - "\"%R%\" -e \"library('rpart.plot')\""  # [win]

about:
  home: http://www.milbo.org/rpart-plot
  license: GPL-3.0-only
  summary: Plot 'rpart' models. Extends plot.rpart() and text.rpart() in the 'rpart' package.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: rpart.plot
# Version: 3.0.7
# Title: Plot 'rpart' Models: An Enhanced Version of 'plot.rpart'
# Author: Stephen Milborrow
# Maintainer: Stephen Milborrow <milbo@sonic.net>
# Depends: R (>= 3.4.0), rpart (>= 4.1-10)
# Suggests: earth (>= 5.1.0)
# Description: Plot 'rpart' models. Extends plot.rpart() and text.rpart() in the 'rpart' package.
# License: GPL-3
# LazyData: yes
# URL: http://www.milbo.org/rpart-plot
# NeedsCompilation: no
# Packaged: 2019-04-12 02:52:17 UTC; milbo
# Repository: CRAN
# Date/Publication: 2019-04-12 10:52:52 UTC
