appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: ER6vjU3DPHt5HBoui7uCfDvgXk9aBqc/JFMFavxNGnh0umP8/Ja+RBOKWPLDblg7rt4j8BqpRZLfd5MNXweNS/0V8Xp++HZftzPiWeReeZS8OSTsCcZ06VbvwjrJCXdjrrS+iVWTKGEPXzoOZIYCnLx+FEJHBQCXF8YAIdVnuRrviUcgKAchJWE80/iFoe3FJQiYxvjeVOOEmRwNcKXQS8XP+Q9Jr7vWx3GzaWgRGtBLr/zkjHkUTQIAV1XM2Cjwi7sP9/YWgNwr0GPFhpcpFpOL22lN0T9YFhtWO/KVwHeawTm0KKRqSACAv/3pDujViWvqdIdpvMjptvKYlcnc42/Eg9QyCZx/CUypL1MeJH/NGhfFMtR7HfHxEf787inLAcl6gcFgSsggq2KUMgxymoUH2KqVIi2pY5dLaFQlArBKmCW+3T05RtKLyFKVSJ/INXl8hTQfXUaBrl5aAnNkSVEhmB+V287yGORaqNCOunSjyfRfGpnvY3IhYIHGUpTxfhEtksUtMS6nGrCN6nAC7+AVDv3upw98nUPsgdRp014Jzd+nYkbceHTuGkLZsZMDBZlYn0RtEENyjxnTzzq/v1on/PNq25yUu/yelzJ/p7+6W1Zj+1bKa4d0i3OcuGayvJ4Vmhr5rqbb8ewp7Km9WH331ZsXqTzPa4HX0fkAFzM=
conda_forge_output_validation: true
